### PR TITLE
Update matrix.py

### PR DESCRIPTION
**Pull request by Forianz**

### CODE REVIEW

**Comment by Forianz** [comment]
ok

**Review by Forianz — COMMENTED** [review]
1

**Comment by kmcnellis** [comment]
Hi @Forianz.  Thanks for sending a PR.  Do you mind giving a short description of what your changes are intended to do?

**Comment by Forianz** [comment]
Hello! Sorry, it was an accident and i didnt find where to unsend it or
undo the changes.

2022. január 24., hétfő dátummal Kiana McNellis ***@***.***>
ezt írta:

**Pull request closed without merging**
